language: php

php:
  - 5.6
  - 7.0
  - 7.1

install:
  - composer create-project --prefer-source --dev --no-interaction zenify/ci vendor/ci @dev
  - . vendor/ci/travis/coverage-init.sh
  - composer update --prefer-source

before_script:
  - . vendor/ci/travis/static-analysis.sh

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS

after_script:
  - . vendor/ci/travis/coverage-send.sh
